### PR TITLE
Support vim-like key bindings for navigation

### PR DESCRIPTION
**Pull request by orhun**
This PR simply adds support for Ctrl-J / Ctrl-K keys for moving up/down and also updates the documentation to use a markdown table for key bindings.

### CODE REVIEW

**Review by grouzen — APPROVED** [review]

**Review by jacek-kurlit — APPROVED** [review]
Thank you for pr
Seems like we are going to need help popup instead of current solution

**Comment by orhun** [comment]
Can you elaborate? What do you mean by popup?

**Comment by jacek-kurlit** [comment]
Like this in lazygit
image

**Comment by orhun** [comment]
Okay, what is the current solution? 👀 I'm not sure if I'm following here

**Comment by jacek-kurlit** [comment]
https://github.com/jacek-kurlit/pik/issues/90

You may ignore my comment I was more talking to myself than to you :)
Current solution is simple help line at the bottom of the screen but the space is limited and I'm planning more search features (like displaying process family) so the time is right to take care of it

**Comment by orhun** [comment]
Ah I see, makes sense :)

**Pull request merged**
